export type Lesson = {
  id: string;
  week: number;
  phaseId: string;
  title: string;
  subtitle: string;
  concepts: string[];
  practice: string[];
  deliverable: string;
  acceptance: string[];
  code: string;
  selfCheck: string;
};

const rows: Array<Omit<Lesson, 'id'>> = [
  {week:1,phaseId:'foundation',title:'模型 API、Token 与流式输出',subtitle:'把 LLM 当成有延迟、有成本、会失败的远程服务。',concepts:['模型输出具有随机性，业务逻辑不能依赖某句文本必然出现。','流式 UI 要维护 connecting、streaming、done、error、cancelled 状态。','API Key 只能留在服务端；同时记录首字延迟、总耗时和 token。'],practice:['封装 TypeScript 模型客户端与错误类型','实现流式渲染、AbortController 取消和有限重试','模拟 429、超时、断流并记录 10 次调用指标'],deliverable:'可观测的流式聊天页',acceptance:['取消后不再追加内容','错误有分类和重试入口','提交延迟与 token 记录'],code:"const controller = new AbortController();\nconst res = await fetch('/api/chat', { method:'POST', signal:controller.signal });\nfor await (const chunk of readStream(res.body)) append(chunk);",selfCheck:'为什么模型调用需要超时、取消和错误分类？'},
  {week:2,phaseId:'foundation',title:'Prompt、结构化输出与验证',subtitle:'把自然语言结果收敛成应用可安全消费的数据。',concepts:['按角色、任务、输入、约束、示例和失败行为组织 Prompt。','Schema 只保证形状，事实、权限和业务规则仍需服务端校验。','把外部文本标为不可信数据，避免混入系统指令。'],practice:['准备 8 条含歧义的产品需求','用 Zod 定义需求提取结构','显示校验错误，并只允许一次格式修复重试'],deliverable:'结构化需求提取器',acceptance:['8 条样本均返回合法结构','重试有明确上限','保留原输入与校验结果'],code:"const Requirement = z.object({\n goal:z.string().min(1), risks:z.array(z.string()).max(8),\n tasks:z.array(z.object({title:z.string(),owner:z.enum(['FE','BE','QA'])}))\n});",selfCheck:'Schema 校验解决了什么，又没有解决什么？'},
  {week:3,phaseId:'tools',title:'工具 Schema 与执行器',subtitle:'模型提出调用意图，应用决定是否执行。',concepts:['工具名、说明和参数影响模型选择，也是安全边界。','工具应小而确定，例如 searchIssues 优于 executeSQL。','参数、返回值、超时和错误都应有稳定协议。'],practice:['实现 searchDocs、getIssue、getBuildStatus、getDiff 四个只读工具','为非法参数、超时和未知工具写测试','界面展示调用摘要和耗时'],deliverable:'四工具知识助手',acceptance:['未知工具不能执行','输入全部经过 Schema','日志可关联会话与调用'],code:"async function execute(name, raw) {\n const tool = registry[name];\n if (!tool) throw new Error('unknown_tool');\n return tool.run(tool.schema.parse(raw));\n}",selfCheck:'为什么工具描述既影响效果，也属于安全设计？'},
  {week:4,phaseId:'tools',title:'Agent Loop、审批与幂等',subtitle:'构建有上限、可审计的工具循环。',concepts:['循环需限制步数、时间、token，并响应取消和不可恢复错误。','模型只能建议动作，权限策略由应用执行。','写操作先预览再审批，并以幂等键抵抗重复执行。'],practice:['实现最多 6 步的工具循环','给 createIssue 增加 draft/confirm 两阶段','模拟确认后网络中断和重复请求'],deliverable:'开发知识助手 v1',acceptance:['循环总能在预算内结束','未确认时无外部写入','重复幂等键只有一个结果'],code:"for (let step=0; step<MAX_STEPS; step++) {\n const turn = await model(state);\n if (turn.final) return turn.final;\n state.push(await policy.execute(turn.toolCall));\n}",selfCheck:'哪些停止条件能防止失控循环？'},
  {week:5,phaseId:'ui',title:'流式 Agent UI 与事件协议',subtitle:'用事件表达真实进度，不从一段文本猜状态。',concepts:['定义 message.delta、tool.started、approval.required、run.failed 等事件。','保存不可变事件，再由 reducer 派生界面。','按 sequence 去重，重连后可安全重放。'],practice:['定义 TypeScript 事件联合类型','实现 SSE 解析器与 reducer','注入重复、乱序和断线事件'],deliverable:'可观察的 Agent 对话界面',acceptance:['事件重放得到同一 UI','工具状态不依赖文本解析','断线有恢复提示'],code:"type Event =\n | {seq:number;type:'message.delta';text:string}\n | {seq:number;type:'tool.started';callId:string;name:string}\n | {seq:number;type:'run.failed';message:string};",selfCheck:'为什么保存事件比只存最终消息更利于恢复？'},
  {week:6,phaseId:'ui',title:'确认、取消、重试与恢复',subtitle:'把关键控制权交还给用户。',concepts:['审批绑定具体工具、目标、参数哈希和过期时间。','取消信号要传播到模型、工具和后台任务。','retry 复用同一动作，rerun 是一次全新运行。'],practice:['制作展示影响范围的审批卡','实现拒绝、过期和参数变化失效','刷新页面后恢复待审批状态'],deliverable:'可中断恢复的审批流程',acceptance:['参数变化后旧审批不可用','取消能停止下游请求','刷新不会重复写入'],code:"type Approval = {\n id:string; runId:string; tool:string; argsHash:string;\n status:'pending'|'approved'|'rejected'|'expired'\n};",selfCheck:'为什么审批必须绑定参数哈希？'},
  {week:7,phaseId:'ui',title:'会话状态与长期记忆',subtitle:'只保存真正需要的事实，并允许查看和删除。',concepts:['数据库历史、模型上下文和长期记忆是三个不同集合。','长对话用相关窗口与摘要控制 token。','记忆应有来源、作用域、更新时间和删除入口。'],practice:['设计 conversations、runs、events 表','实现滚动摘要与上下文预算','增加“记住这条”和记忆管理页'],deliverable:'持久化 Agent 工作台',acceptance:['刷新后会话完整恢复','上下文预算可观测','记忆可追溯且可删除'],code:"type Memory = {\n userId:string; scope:'project'|'global'; key:string;\n value:string; sourceMessageId:string; updatedAt:string\n};",selfCheck:'会话历史、上下文和长期记忆有何区别？'},
  {week:8,phaseId:'rag',title:'文档解析、切分与索引',subtitle:'建立可重复、可增量更新的知识摄取管线。',concepts:['切分应尊重标题、段落、代码块和表格边界。','保存来源、位置、内容哈希、解析器和 embedding 版本。','删除或更新文档必须同步索引。'],practice:['导入 Markdown、PDF 和代码文件','实现结构感知切分','用哈希跳过未变化内容并制作抽查页'],deliverable:'增量文档摄取管线',acceptance:['每个 chunk 可回到原文','删除文档会删除相关向量','相同内容不会重复索引'],code:"type Chunk = {\n id:string; documentId:string; headings:string[]; text:string;\n start:number; end:number; contentHash:string\n};",selfCheck:'哪些元数据让检索结果可以被引用和重建？'},
  {week:9,phaseId:'rag',title:'向量、关键词与重排',subtitle:'用可测量的检索组合找到真正相关的证据。',concepts:['向量擅长语义，BM25 擅长错误码和专有名词。','RRF 可合并不同分数尺度的排名。','先召回候选，再重排和去重，最后控制上下文预算。'],practice:['准备 30 条带标准来源的问题','比较关键词、向量和混合检索','统计 Recall@5、MRR 并分析 5 个失败样本'],deliverable:'检索评测报告',acceptance:['策略使用同一语料和问题','指标可一键重跑','重排收益有数据依据'],code:"const merged = reciprocalRankFusion(vectorHits, keywordHits);\nconst ranked = await rerank(query, merged.slice(0,30));\nreturn diversify(ranked).slice(0,6);",selfCheck:'为什么 RRF 适合合并关键词与向量排名？'},
  {week:10,phaseId:'rag',title:'引用、拒答与 RAG 评测',subtitle:'让答案可核验，并在证据不足时停下来。',concepts:['关键陈述应映射到具体 chunk 和原文位置。','生成后校验引用存在且确实支持陈述。','把检索失败、生成忽略和引用错误分别评测。'],practice:['实现带 chunkId 的回答协议','加入证据不足拒答阈值','记录召回、忠实度和引用准确率'],deliverable:'带引用的文档问答系统',acceptance:['事实可点击回原文','无证据问题明确拒答','30 条评测可复现'],code:"function validCitation(c, chunks) {\n const source = chunks.get(c.chunkId);\n return Boolean(source && source.includes(c.quote));\n}",selfCheck:'如何区分一次错误回答是检索问题还是生成问题？'},
  {week:11,phaseId:'workflow',title:'确定性工作流与状态机',subtitle:'用业务流程控制模型，而不是反过来。',concepts:['审批、门禁等确定规则写成代码；模糊任务才交给模型。','节点定义结构化输入输出，非法状态迁移应被拒绝。','每步记录输入版本、输出、耗时和错误。'],practice:['画需求分析状态图','用 Zod 定义节点契约','注入节点失败并验证状态'],deliverable:'需求分析工作流骨架',acceptance:['非法迁移被拒绝','节点可独立测试','失败保留诊断上下文'],code:"const next = {\n intake:['research','failed'], research:['plan','failed'],\n plan:['approval','failed'], approval:['execute','failed'],\n execute:['done','failed'], done:[], failed:[]\n};",selfCheck:'哪些步骤适合确定性代码，哪些适合模型？'},
  {week:12,phaseId:'workflow',title:'子任务、并发与多 Agent',subtitle:'只在职责和上下文真正可分离时拆 Agent。',concepts:['独立上下文、权限或可并行执行才是拆分理由。','子任务返回发现、证据、置信度和未决问题。','协调者必须处理重复、冲突和部分失败。'],practice:['把仓库分析拆为 UI/API/Test 子任务','限制各自工具和步数','并行执行并汇总冲突结果'],deliverable:'并行影响分析器',acceptance:['单任务失败不丢其他结果','每个结论带证据','能解释拆分的收益与成本'],code:"type Finding = {claim:string;evidence:string[];confidence:number};\nconst results = await Promise.allSettled(tasks.map(runBoundedSubtask));",selfCheck:'什么情况下子 Agent 比普通函数更合适？'},
  {week:13,phaseId:'workflow',title:'异步任务、检查点与幂等',subtitle:'让长任务经历重启与重试后仍正确结束。',concepts:['API 返回 runId，Worker 异步执行，客户端订阅事件。','任务状态要覆盖 queued、running、waiting、done、failed、cancelled。','至少一次投递要求处理器可重入且幂等。'],practice:['将流程迁移到后台队列','每个节点保存 checkpoint','重复投递任务 10 次并重启 Worker'],deliverable:'可恢复的后台工作流',acceptance:['重复投递只有一个业务结果','重启从检查点继续','取消不会被晚到结果覆盖'],code:"const prior = await db.result.findUnique({where:{key:job.key}});\nif (prior) return prior;\nreturn db.transaction(tx => executeAndPersist(tx, job));",selfCheck:'为什么队列重试要求处理器幂等？'},
  {week:14,phaseId:'mcp',title:'构建 MCP Server',subtitle:'把能力包装成可发现、可组合的标准接口。',concepts:['Server 暴露 Tools、Resources 或 Prompts；Host 决定体验和权限。','描述与 Schema 影响模型是否正确调用。','协议标准化连接，不替代业务授权。'],practice:['创建 TypeScript MCP Server','实现 search、read、list 三个只读工具','用 Inspector 验证 Schema 与错误'],deliverable:'仓库知识 MCP Server',acceptance:['能力可被客户端发现','路径限制在工作区','错误不泄露密钥和系统路径'],code:"server.tool('search_repository', {\n query:z.string(), limit:z.number().min(1).max(20)\n}, async args => ({content:await search(args)}));",selfCheck:'MCP Server、Client、Host 分别负责什么？'},
  {week:15,phaseId:'mcp',title:'MCP Client、安全与写工具',subtitle:'在明确的信任边界内连接外部系统。',concepts:['第三方 Server 的说明和输出都属于不可信输入。','配置工具允许列表、超时、输出上限和凭据作用域。','写操作使用草稿、预览、绑定审批和审计。'],practice:['连接上一周 Server','实现允许列表、超时和输出截断','给 createIssue 做 draft/confirm 两阶段'],deliverable:'安全的 MCP 集成 Demo',acceptance:['未授权工具无法调用','写入必须明确确认','恶意大输出被截断并标记'],code:"const policy = {\n allowTools:['search_repository','read_file','draft_issue'],\n requireApproval:['create_issue'], maxOutputBytes:200000, timeoutMs:10000\n};",selfCheck:'MCP 兼容为什么不代表 Server 值得信任？'},
  {week:16,phaseId:'backend',title:'API、鉴权与限流',subtitle:'为 Agent 建立清晰的服务端边界。',concepts:['认证之后仍需按资源所有权或角色授权。','不能信任浏览器提交的 userId，工具也不能绕过授权。','按请求、并发、token 和昂贵工具次数综合限流。'],practice:['设计 runs、messages、approvals API','实现会话认证和跨用户访问测试','增加并发与每日 token 限额'],deliverable:'带鉴权的 Agent API',acceptance:['越权测试通过','错误结构统一','限流不留下半创建任务'],code:"app.post('/runs', auth, rateLimit, async (req,res) => {\n const input = RunInput.parse(req.body);\n res.status(202).json(await createRun({...input,userId:req.user.id}));\n});",selfCheck:'Agent 工具为什么不能绕过 API 的资源授权？'},
  {week:17,phaseId:'backend',title:'PostgreSQL 与 pgvector',subtitle:'关系数据保存真相，向量索引加速相似检索。',concepts:['关键状态用外键、唯一约束和 CHECK 保证一致性。','JSONB 适合易变载荷，常查字段应独立成列。','HNSW 与 IVFFlat 的选择需用真实规模评测。'],practice:['建立迁移和种子数据','事务创建 run 与首事件','对 10 万 chunk 测延迟和 Recall@5'],deliverable:'持久化数据层与基准报告',acceptance:['约束阻止非法状态','迁移可前进和回滚','向量参数有实测依据'],code:"CREATE TABLE runs (\n id uuid PRIMARY KEY, user_id uuid NOT NULL,\n status text CHECK (status IN ('queued','running','waiting','done','failed')),\n idempotency_key text UNIQUE\n);",selfCheck:'哪些一致性应交给数据库约束？'},
  {week:18,phaseId:'backend',title:'Redis、BullMQ、Docker 与交付',subtitle:'把 Web、Worker、数据库和队列组成可运行系统。',concepts:['Web 负责校验和入队，Worker 控制并发并更新状态。','仅瞬时错误重试，业务错误直接失败或等待处理。','生产还需迁移、健康检查、优雅退出、备份与观测。'],practice:['实现 Web 入队与 Worker 消费','处理 SIGTERM 和 retryable 错误','用 Compose 启动四个服务'],deliverable:'一键启动的多服务系统',acceptance:['Compose 可完成样例任务','重启 Worker 不丢任务','健康检查覆盖真实依赖'],code:"const worker = new Worker('agent-runs', processRun, {\n connection, concurrency:4,\n settings:{backoffStrategy:n=>Math.min(30000,2**n*500)}\n});",selfCheck:'哪些错误应重试，哪些必须立即失败？'},
  {week:19,phaseId:'production',title:'评测数据集与质量指标',subtitle:'把“感觉不错”变成可回归的工程证据。',concepts:['分类、提取、工具选择、RAG 需要不同指标。','数据集应覆盖常见、长尾、无答案、恶意输入和历史事故。','保留独立测试集，防止对样本过拟合。'],practice:['收集并匿名化 50 条样本','实现任务成功、引用、工具准确率评分','在 CI 中比较基线与候选版本'],deliverable:'可重复的评测套件',acceptance:['覆盖至少 5 类风险','报告质量、延迟和成本','退化会阻止发布'],code:"const report = await evaluate(dataset, candidate, {\n metrics:[taskSuccess,citationFaithfulness,toolAccuracy,latency,cost]\n});",selfCheck:'为什么一个总分不足以指导 Agent 优化？'},
  {week:20,phaseId:'production',title:'Tracing、日志、成本与 SLO',subtitle:'沿一次运行看清模型、检索、工具与队列。',concepts:['runId/traceId 贯穿 API、队列、模型和工具。','Span 记录耗时、状态、token 和重试，正文默认脱敏。','SLO 应对应用户影响并配套 Runbook。'],practice:['为完整运行添加 trace','制作成功率、p95、token、成本面板','定义 3 个 SLO 和告警手册'],deliverable:'观测面板与运行手册',acceptance:['runId 可定位所有步骤','成本可按用户和功能聚合','日志不含密钥与敏感正文'],code:"span.setAttributes({\n 'agent.run_id':runId, 'llm.model':model,\n 'llm.input_tokens':usage.input, 'tool.name':toolName\n});",selfCheck:'哪些 Span 能区分模型慢、排队慢和工具慢？'},
  {week:21,phaseId:'production',title:'Prompt Injection 与最小权限',subtitle:'把外部文本视作数据，把动作限制在策略内。',concepts:['注入无法只靠 Prompt 消除，需隔离指令与数据。','用最小凭据、租户隔离、网络允许列表和审批限制后果。','即使模型被控制，也不应拥有越权能力。'],practice:['画数据流和信任边界','编写 20 条注入与越权测试','给 URL 获取加入 SSRF 防护'],deliverable:'威胁模型与安全报告',acceptance:['攻击测试进入 CI','跨租户数据不可见','高影响动作始终需审批'],code:"function authorize(call, ctx) {\n assertAllowedTool(call.name); assertOwnership(call.args,ctx.userId);\n assertAllowedDestination(call.args.url);\n if (isHighImpact(call)) return requireApproval(call);\n}",selfCheck:'模型若完全被注入控制，哪些边界仍能避免事故？'},
  {week:22,phaseId:'production',title:'毕业项目架构与范围',subtitle:'把作品压缩成可交付的垂直切片。',concepts:['核心路径是读需求、检索仓库、影响分析和人工确认。','按实时/异步、读/写、可信/不可信划分边界。','明确非目标，避免第一版连接所有平台。'],practice:['写一页 PRD 和成功指标','画组件、序列与数据模型图','列出 10 个风险并拆三次演示里程碑'],deliverable:'毕业项目架构设计包',acceptance:['核心路径两周可完成','外部写入有明确边界','README 写明非目标'],code:"Browser -> Web API -> Queue -> Worker -> Model\n                       |         |-> Retrieval\n                       |         |-> Tools + Approval\n                       -> Postgres <- Events",selfCheck:'架构中哪三个边界最值得优先测试？'},
  {week:23,phaseId:'production',title:'毕业项目实现与硬化',subtitle:'完成真实链路，用故障注入证明能恢复。',concepts:['每个里程碑都应从 UI 到数据库可演示。','先只读分析，再做草稿，最后才允许审批后写入。','主动注入 429、超时、重启和重复投递。'],practice:['完成需求、检索、计划和审批链路','补齐单元、集成与 E2E','运行故障注入并修复重复副作用'],deliverable:'前端研发协作 Agent RC',acceptance:['核心 E2E 稳定通过','故障不产生重复写入','用户可见证据和执行状态'],code:"const scenarios = [\n 'model_rate_limit','tool_timeout','worker_restart',\n 'duplicate_delivery','approval_expired','db_unavailable'\n];",selfCheck:'哪类故障最可能造成不可逆副作用？'},
  {week:24,phaseId:'production',title:'部署、评测报告与作品表达',subtitle:'让别人能打开、理解并验证你的能力。',concepts:['上线要验证域名、TLS、密钥、迁移、备份、监控和回滚。','README 先讲用户问题和结果，再讲架构与权衡。','真实指标、失败案例和已知限制比宣传语更可信。'],practice:['部署 Demo 并做冒烟测试','生成质量、延迟、成本、安全报告','录制 3 分钟演示并邀请 3 位用户试用'],deliverable:'在线 Demo、README、评测与复盘',acceptance:['陌生人可按 README 启动','线上核心路径可体验','指标与限制有证据','5 分钟能讲清关键权衡'],code:"releaseChecklist({\n migrations:'applied', smokeTests:'passed', evals:'passed',\n secrets:'scoped', dashboards:'ready', rollback:'tested'\n});",selfCheck:'什么证据最能说明你已具备 Agent 工程能力？'}
];

export const lessons: Lesson[] = rows.map(item => ({
  ...item,
  id: `week-${String(item.week).padStart(2, '0')}`
}));

export const lessonsByPhase = (phaseId: string) => lessons.filter(item => item.phaseId === phaseId);
